version: '3'

services:
  app:
    image: node:10-alpine
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    ports:
      - 8080:8080
    depends_on:
      - api

  api:
    build: ./api
    command: python3 manage.py runserver 0.0.0.0:8888
    volumes:
      - ./api:/code
    ports:
      - 8888:8888
